name: Docs
on: [push, pull_request]
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install doc requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r doc_requirements.txt
      - name: Build docs
        run: |
          sphinx-build -b html docs/source/ docs/build/html
