name: Docs
on: [push, pull_request]
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Sphinx
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
      - name: Build docs
        run: |
          sphinx-build -b html docs/source/ docs/build/html
      - name: Upload artifacts (attach HTML pages to action)
        uses: actions/upload-artifact@v1
        with:
          name: html-docs
          path: docs/build/html/
