# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Examples

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install MPI
      run: |
        sudo apt-get update
        sudo apt-get install -y mpich libmpich-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter
        pip install nbconvert
        pip install matplotlib
        pip install -r requirements.txt
    - name: Build bingocpp
      run: |
        ./.build_bingocpp.sh
    - name: Run examples
      run: |
        examples/.test_examples.sh
      env:
        PYTHONPATH: "."
